/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import com.github.kwhat.jnativehook.GlobalScreen;
import com.github.kwhat.jnativehook.NativeHookException;

import game.Classes.GlobalKeyListener;
import game.Classes.Slots;

public class App {
    private static Slots slots;
    private static GlobalKeyListener globalKeylistner = new GlobalKeyListener();

    private final static String spinStr = "\r\nPress space to spin or ESC to exit";
    private final static String creditsStr = "\r\nCredits has been added";

    public static void main(String[] args) {
        boolean fakeWin = false;

        if(args.length > 0){
            fakeWin = Boolean.parseBoolean(args[0]);
        }

        Init(fakeWin);                    
        System.out.println(spinStr);

        while(true) {
            try{
                Thread.sleep(100);
            }      
            catch(InterruptedException ex){
                System.err.println(ex.getMessage());
                System.exit(1);
            }
         }
    }
      
    private static void Init(boolean fakeWin){
        slots =  new Slots(fakeWin);
        
        try {
			GlobalScreen.registerNativeHook();
		}
		catch (NativeHookException ex) {
		    System.exit(1);
		}

		GlobalScreen.addNativeKeyListener(globalKeylistner);
        InitGlobalKeyEventsListner();
    }

    private static void InitGlobalKeyEventsListner()
    {
        globalKeylistner.endKeyEventListner = () -> {
            System.exit(1);
        };

        globalKeylistner.spinKeyEventListner = () -> {
            slots.Spin();
            System.out.println(spinStr);
        };

        globalKeylistner.addAddCreditsKeyEvent = () -> {
            slots.AddCredits();
            System.out.println(creditsStr);
        };
    }
}
